#!/usr/bin/env bash
set -euo pipefail

# Usage: ./scripts/generate-backend-env.sh <environment> <aws-region> <rds-endpoint>
# Example: ./scripts/generate-backend-env.sh prod ap-southeast-2 flora-db-production.cbm26q24g3sj.ap-southeast-2.rds.amazonaws.com

ENVIRONMENT=${1:-prod}
AWS_REGION=${2:-ap-southeast-2}
RDS_ENDPOINT=${3:-}

if [[ -z "${RDS_ENDPOINT}" ]]; then
  echo "error: missing RDS endpoint hostname (third argument)" >&2
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/apps/backend/.env"

ssm_plain() {
  local name=$1
  aws ssm get-parameter \
    --name "/flora/${ENVIRONMENT}/${name}" \
    --query 'Parameter.Value' \
    --output text \
    --region "${AWS_REGION}"
}

ssm_secure() {
  local name=$1
  aws ssm get-parameter \
    --name "/flora/${ENVIRONMENT}/${name}" \
    --with-decryption \
    --query 'Parameter.Value' \
    --output text \
    --region "${AWS_REGION}"
}

DB_USER=$(ssm_plain "db_username")
DB_PASSWORD=$(ssm_secure "db_password")
AUTH0_DOMAIN=$(ssm_plain "auth0_domain")
AUTH0_CLIENT_ID=$(ssm_plain "auth0_client_id")
AUTH0_CLIENT_SECRET=$(ssm_secure "auth0_client_secret")
AUTH0_AUDIENCE=$(ssm_plain "auth0_audience")
STRIPE_SECRET_KEY=$(ssm_secure "stripe_secret_key")
STRIPE_PUBLISHABLE_KEY=$(ssm_plain "stripe_publishable_key")
STRIPE_WEBHOOK_SECRET=$(ssm_secure "stripe_webhook_secret")
STRIPE_WEEKLY_PRICE_ID=$(ssm_plain "stripe_weekly_price_id")
STRIPE_BIWEEKLY_PRICE_ID=$(ssm_plain "stripe_biweekly_price_id")
STRIPE_MONTHLY_PRICE_ID=$(ssm_plain "stripe_monthly_price_id")
STRIPE_SPONTANEOUS_PRICE_ID=$(ssm_plain "stripe_spontaneous_price_id")
GMAIL_USER=$(ssm_plain "gmail_user")
GMAIL_PASSWORD=$(ssm_secure "gmail_password")
GEMINI_API_KEY=$(ssm_secure "gemini_api_key")
JWT_SECRET=$(ssm_secure "jwt_secret")

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/generate-backend-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
NODE_ENV=production
PORT=3001

DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${RDS_ENDPOINT}:5432/flora_db

AUTH0_DOMAIN=${AUTH0_DOMAIN}
AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
AUTH0_AUDIENCE=${AUTH0_AUDIENCE}

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_WEEKLY_PRICE_ID=${STRIPE_WEEKLY_PRICE_ID}
STRIPE_BIWEEKLY_PRICE_ID=${STRIPE_BIWEEKLY_PRICE_ID}
STRIPE_MONTHLY_PRICE_ID=${STRIPE_MONTHLY_PRICE_ID}
STRIPE_SPONTANEOUS_PRICE_ID=${STRIPE_SPONTANEOUS_PRICE_ID}

GMAIL_USER=${GMAIL_USER}
GMAIL_PASSWORD=${GMAIL_PASSWORD}

GEMINI_API_KEY=${GEMINI_API_KEY}
JWT_SECRET=${JWT_SECRET}

FRONTEND_URL=https://dzmu16crq41il.cloudfront.net
EOF

echo "Wrote ${ENV_FILE} with fresh secrets from SSM."
